# Generated by Django 3.2.16 on 2022-10-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('內場', '內場'), ('外場', '外場'), ('管理', '管理'), ('開發', '開發'), ('其他', '其他')], default='其他', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
