# Generated by Django 3.2.16 on 2022-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20221020_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchlocation',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
